export const allCountries = [
    'Afganistan',
    'Albania',
    'Algieria',
    'Andora',
    'Angola',
    'Antigua i Barbuda',
    'Arabia Saudyjska',
    'Argentyna',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbejdżan',
    'Bahamy',
    'Bahrajn',
    'Bangladesz',
    'Barbados',
    'Belgia',
    'Belize',
    'Benin',
    'Bhutan',
    'Białoruś',
    'Boliwia',
    'Bośnia i Hercegowina',
    'Botswana',
    'Brazylia',
    'Brunei',
    'Bułgaria',
    'Burkina Faso',
    'Burundi',
    'Chile',
    'Chiny',
    'Chorwacja',
    'Cypr',
    'Czad',
    'Czarnogóra',
    'Czechy',
    'Dania',
    'Demokratyczna Republika Konga',
    'Dominika',
    'Dominikana',
    'Dżibuti',
    'Egipt',
    'Ekwador',
    'Erytrea',
    'Estonia',
    'Eswatini',
    'Etiopia',
    'Fidżi',
    'Filipiny',
    'Finlandia',
    'Francja',
    'Gabon',
    'Gambia',
    'Ghana',
    'Grecja',
    'Grenada',
    'Gruzja',
    'Gujana',
    'Gwatemala',
    'Gwinea',
    'Gwinea Bissau',
    'Gwinea Równikowa',
    'Haiti',
    'Hiszpania',
    'Holandia',
    'Honduras',
    'Indie',
    'Indonezja',
    'Irak',
    'Iran',
    'Irlandia',
    'Islandia',
    'Izrael',
    'Jamajka',
    'Japonia',
    'Jemen',
    'Jordania',
    'Kambodża',
    'Kamerun',
    'Kanada',
    'Katar',
    'Kazachstan',
    'Kenia',
    'Kirgistan',
    'Kiribati',
    'Kolumbia',
    'Komory',
    'Kongo',
    'Korea Południowa',
    'Korea Północna',
    'Kostaryka',
    'Kuba',
    'Kuwejt',
    'Laos',
    'Lesotho',
    'Liban',
    'Liberia',
    'Libia',
    'Liechtenstein',
    'Litwa',
    'Luksemburg',
    'Łotwa',
    'Macedonia Północna',
    'Madagaskar',
    'Malawi',
    'Malediwy',
    'Malezja',
    'Mali',
    'Malta',
    'Maroko',
    'Mauretania',
    'Mauritius',
    'Meksyk',
    'Mikronezja',
    'Mjanma',
    'Mołdawia',
    'Monako',
    'Mongolia',
    'Mozambik',
    'Namibia',
    'Nauru',
    'Nepal',
    'Niemcy',
    'Niger',
    'Nigeria',
    'Nikaragua',
    'Norwegia',
    'Nowa Zelandia',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua-Nowa Gwinea',
    'Paragwaj',
    'Peru',
    'Polska',
    'Południowa Afryka',
    'Portugalia',
    'Republika Środkowoafrykańska',
    'Republika Zielonego Przylądka',
    'Rosja',
    'Rumunia',
    'Rwanda',
    'Saint Kitts i Nevis',
    'Saint Lucia',
    'Saint Vincent i Grenadyny',
    'Salwador',
    'Samoa',
    'San Marino',
    'Senegal',
    'Serbia',
    'Seszele',
    'Sierra Leone',
    'Singapur',
    'Słowacja',
    'Słowenia',
    'Somalia',
    'Sri Lanka',
    'Stany Zjednoczone',
    'Sudan',
    'Sudan Południowy',
    'Surinam',
    'Syria',
    'Szwajcaria',
    'Szwecja',
    'Tadżykistan',
    'Tajlandia',
    'Tanzania',
    'Timor Wschodni',
    'Togo',
    'Tonga',
    'Trynidad i Tobago',
    'Tunezja',
    'Turcja',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraina',
    'Urugwaj',
    'Uzbekistan',
    'Vanuatu',
    'Watykan',
    'Wenezuela',
    'Węgry',
    'Wielka Brytania',
    'Wietnam',
    'Włochy',
    'Wybrzeże Kości Słoniowej',
    'Wyspy Marshalla',
    'Wyspy Salomona',
    'Wyspy Świętego Tomasza i Książęca',
    'Zambia',
    'Zimbabwe',
    'Zjednoczone Emiraty Arabskie'
]

export const allPhonePrefixes = [
    {value: '+995 44', label: '+995 44 Abchazja'},
    {value: '+93', label: '+93 Afganistan'},
    {value: '+355', label: '+355 Albania'},
    {value: '+213', label: '+213 Algieria'},
    {value: '+1 268', label: '+1 268 Antigua i Barbuda'},
    {value: '+966', label: '+966 Arabia Saudyjska'},
    {value: '+54', label: '+54 Argentyna'},
    {value: '+374', label: '+374 Armenia'},
    {value: '+297', label: '+297 Aruba'},
    {value: '+61', label: '+61 Australia'},
    {value: '+43', label: '+43 Austria'},
    {value: '+994', label: '+994 Azerbejdżan'},
    {value: '+1 242', label: '+1 242 Bahamy'},
    {value: '+973', label: '+973 Bahrajn'},
    {value: '+880', label: '+880 Bangladesz'},
    {value: '+1 246', label: '+1 246 Barbados'},
    {value: '+32', label: '+32 Belgia'},
    {value: '+229', label: '+229 Benin'},
    {value: '+1 441', label: '+1 441 Bermudy'},
    {value: '+975', label: '+975 Bhutan'},
    {value: '+375', label: '+375 Białoruś'},
    {value: '+95', label: '+95 Birma'},
    {value: '+387', label: '+387 Bośnia i Hercegowina'},
    {value: '+267', label: '+267 Botswana'},
    {value: '+55', label: '+55 Brazylia'},
    {value: '+1 284', label: '+1 284 Brytyjskie Wyspy Dziewicze'},
    {value: '+359', label: '+359 Bułgaria'},
    {value: '+226', label: '+226 Burkina Faso'},
    {value: '+56', label: '+56 Chile'},
    {value: '+86', label: '+86 Chiny'},
    {value: '+385', label: '+385 Chorwacja'},
    {value: '+357', label: '+357 Cypr'},
    {value: '+382', label: '+382 Czarnogóra'},
    {value: '+420', label: '+420 Czechy'},
    {value: '+45', label: '+45 Dania'},
    {value: '+1 809', label: '+1 809 Dominikana'},
    {value: '+20', label: '+20 Egipt'},
    {value: '+593', label: '+593 Ekwador'},
    {value: '+372', label: '+372 Estonia'},
    {value: '+500', label: '+500 Falklandy'},
    {value: '+63', label: '+63 Filipiny'},
    {value: '+358', label: '+358 Finlandia'},
    {value: '+33', label: '+33 Francja'},
    {value: '+241', label: '+241 Gabon'},
    {value: '+220', label: '+220 Gambia'},
    {value: '+233', label: '+233 Ghana'},
    {value: '+30', label: '+30 Grecja'},
    {value: '+1 473', label: '+1 473 Grenada'},
    {value: '+299', label: '+299 Grenlandia'},
    {value: '+995', label: '+995 Gruzja'},
    {value: '+592', label: '+592 Gujana'},
    {value: '+509', label: '+509 Haiti'},
    {value: '+34', label: '+34 Hiszpania'},
    {value: '+31', label: '+31 Holandia'},
    {value: '+852', label: '+852 Hongkong'},
    {value: '+91', label: '+91 Indie'},
    {value: '+62', label: '+62 Indonezja'},
    {value: '+964', label: '+964 Irak'},
    {value: '+98', label: '+98 Iran'},
    {value: '+353', label: '+353 Irlandia'},
    {value: '+354', label: '+354 Islandia'},
    {value: '+972', label: '+972 Izrael'},
    {value: '+1 876', label: '+1 876 Jamajka'},
    {value: '+81', label: '+81 Japonia'},
    {value: '+962', label: '+962 Jordania'},
    {value: '+1 345', label: '+1 345 Kajmany'},
    {value: '+855', label: '+855 Kambodża'},
    {value: '+237', label: '+237 Kamerun'},
    {value: '+974', label: '+974 Katar'},
    {value: '+254', label: '+254 Kenia'},
    {value: '+996', label: '+996 Kirgistan'},
    {value: '+57', label: '+57 Kolumbia'},
    {value: '+82', label: '+82 Korea Południowa'},
    {value: '+850', label: '+850 Korea Północna'},
    {value: '+506', label: '+506 Kostaryka'},
    {value: '+53', label: '+53 Kuba'},
    {value: '+961', label: '+961 Liban'},
    {value: '+423', label: '+423 Liechtenstein'},
    {value: '+370', label: '+370 Litwa'},
    {value: '+352', label: '+352 Luksemburg'},
    {value: '+371', label: '+371 Łotwa'},
    {value: '+389', label: '+389 Macedonia'},
    {value: '+60', label: '+60 Malezja'},
    {value: '+356', label: '+356 Malta'},
    {value: '+212', label: '+212 Maroko'},
    {value: '+596', label: '+596 Martynika'},
    {value: '+230', label: '+230 Mauritius'},
    {value: '+52', label: '+52 Meksyk'},
    {value: '+377', label: '+377 Monako'},
    {value: '+976', label: '+976 Mongolia'},
    {value: '+264', label: '+264 Namibia'},
    {value: '+977', label: '+977 Nepal'},
    {value: '+49', label: '+49 Niemcy'},
    {value: '+234', label: '+234 Nigeria'},
    {value: '+47', label: '+47 Norwegia'},
    {value: '+64', label: '+64 Nowa Zelandia'},
    {value: '+968', label: '+968 Oman'},
    {value: '+92', label: '+92 Pakistan'},
    {value: '+507', label: '+507 Panama'},
    {value: '+51', label: '+51 Peru'},
    {value: '+689', label: '+689 Polinezja Francuska'},
    {value: '+48', label: '+48 Polska'},
    {value: '+1 787', label: '+1 787 Portoryko'},
    {value: '+351', label: '+351 Portugalia'},
    {value: '+27', label: '+27 Republika Południowej Afryki'},
    {value: '+7', label: '+7 Rosja, Kazachstan'},
    {value: '+40', label: '+40 Rumunia'},
    {value: '+1 758', label: '+1 758 Saint Lucia'},
    {value: '+378', label: '+378 San Marino'},
    {value: '+381', label: '+381 Serbia'},
    {value: '+65', label: '+65 Singapur'},
    {value: '+421', label: '+421 Słowacja'},
    {value: '+386', label: '+386 Słowenia'},
    {value: '+94', label: '+94 Sri Lanka'},
    {value: '+1', label: '+1 Stany Zjednoczone, Kanada'},
    {value: '+268', label: '+268 Suazi'},
    {value: '+963', label: '+963 Syria'},
    {value: '+41', label: '+41 Szwajcaria'},
    {value: '+46', label: '+46 Szwecja'},
    {value: '+992', label: '+992 Tadżykistan'},
    {value: '+66', label: '+66 Tajlandia'},
    {value: '+886', label: '+886 Tajwan'},
    {value: '+255', label: '+255 Tanzania'},
    {value: '+1 868', label: '+1 868 Trynidad i Tobago'},
    {value: '+216', label: '+216 Tunezja'},
    {value: '+90', label: '+90 Turcja'},
    {value: '+993', label: '+993 Turkmenistan'},
    {value: '+380', label: '+380 Ukraina'},
    {value: '+598', label: '+598 Urugwaj'},
    {value: '+998', label: '+998 Uzbekistan'},
    {value: '+58', label: '+58 Wenezuela'},
    {value: '+36', label: '+36 Węgry'},
    {value: '+44', label: '+44 Wielka Brytania'},
    {value: '+84', label: '+84 Wietnam'},
    {value: '+39', label: '+39 Włochy'},
    {value: '+1 340', label: '+1 340 Wyspy Dziewicze Stanów Zjednoczonych'},
    {value: '+263', label: '+263 Zimbabwe'},
    {value: '+971', label: '+971 Zjednoczone Emiraty Arabskie'}
]